package com.zts.educational.admin.mapper;

import com.zts.educational.admin.model.domain.BaseMenu;
import com.zts.educational.admin.model.domain.BaseMenuExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BaseMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    long countByExample(BaseMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    int deleteByExample(BaseMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    int insert(BaseMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    int insertSelective(BaseMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    List<BaseMenu> selectByExample(BaseMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    BaseMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    BaseMenu selectByGuid(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BaseMenu record, @Param("example") BaseMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BaseMenu record, @Param("example") BaseMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BaseMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BaseMenu record);
}