package com.zts.educational.admin.model.domain;

import com.sfsctech.core.base.domain.dto.BaseDto;

public class BaseSystem extends BaseDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_system.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_system.Guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_system.Code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_system.NameCn
     *
     * @mbg.generated
     */
    private String namecn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_system.NameEn
     *
     * @mbg.generated
     */
    private String nameen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_system.Domain
     *
     * @mbg.generated
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_system.Url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_system.Type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_system.Status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_system.ID
     *
     * @return the value of base_system.ID
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_system.ID
     *
     * @param id the value for base_system.ID
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_system.Guid
     *
     * @return the value of base_system.Guid
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_system.Guid
     *
     * @param guid the value for base_system.Guid
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_system.Code
     *
     * @return the value of base_system.Code
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_system.Code
     *
     * @param code the value for base_system.Code
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_system.NameCn
     *
     * @return the value of base_system.NameCn
     * @mbg.generated
     */
    public String getNamecn() {
        return namecn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_system.NameCn
     *
     * @param namecn the value for base_system.NameCn
     * @mbg.generated
     */
    public void setNamecn(String namecn) {
        this.namecn = namecn == null ? null : namecn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_system.NameEn
     *
     * @return the value of base_system.NameEn
     * @mbg.generated
     */
    public String getNameen() {
        return nameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_system.NameEn
     *
     * @param nameen the value for base_system.NameEn
     * @mbg.generated
     */
    public void setNameen(String nameen) {
        this.nameen = nameen == null ? null : nameen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_system.Domain
     *
     * @return the value of base_system.Domain
     * @mbg.generated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_system.Domain
     *
     * @param domain the value for base_system.Domain
     * @mbg.generated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_system.Url
     *
     * @return the value of base_system.Url
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_system.Url
     *
     * @param url the value for base_system.Url
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_system.Type
     *
     * @return the value of base_system.Type
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_system.Type
     *
     * @param type the value for base_system.Type
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_system.Status
     *
     * @return the value of base_system.Status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_system.Status
     *
     * @param status the value for base_system.Status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}