package com.zts.educational.admin.model.domain;


import com.sfsctech.core.base.domain.dto.BaseDto;

public class BaseMenu extends BaseDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.Guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.Parent
     *
     * @mbg.generated
     */
    private String parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.SysGuid
     *
     * @mbg.generated
     */
    private String sysguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.SysCode
     *
     * @mbg.generated
     */
    private String syscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.Code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.Url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.Description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.Sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.isLeaf
     *
     * @mbg.generated
     */
    private Boolean isleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_menu.Status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.ID
     *
     * @return the value of base_menu.ID
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.ID
     *
     * @param id the value for base_menu.ID
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.Guid
     *
     * @return the value of base_menu.Guid
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.Guid
     *
     * @param guid the value for base_menu.Guid
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.Parent
     *
     * @return the value of base_menu.Parent
     * @mbg.generated
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.Parent
     *
     * @param parent the value for base_menu.Parent
     * @mbg.generated
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.SysGuid
     *
     * @return the value of base_menu.SysGuid
     * @mbg.generated
     */
    public String getSysguid() {
        return sysguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.SysGuid
     *
     * @param sysguid the value for base_menu.SysGuid
     * @mbg.generated
     */
    public void setSysguid(String sysguid) {
        this.sysguid = sysguid == null ? null : sysguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.SysCode
     *
     * @return the value of base_menu.SysCode
     * @mbg.generated
     */
    public String getSyscode() {
        return syscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.SysCode
     *
     * @param syscode the value for base_menu.SysCode
     * @mbg.generated
     */
    public void setSyscode(String syscode) {
        this.syscode = syscode == null ? null : syscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.Code
     *
     * @return the value of base_menu.Code
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.Code
     *
     * @param code the value for base_menu.Code
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.Name
     *
     * @return the value of base_menu.Name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.Name
     *
     * @param name the value for base_menu.Name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.Url
     *
     * @return the value of base_menu.Url
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.Url
     *
     * @param url the value for base_menu.Url
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.Description
     *
     * @return the value of base_menu.Description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.Description
     *
     * @param description the value for base_menu.Description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.Sort
     *
     * @return the value of base_menu.Sort
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.Sort
     *
     * @param sort the value for base_menu.Sort
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.isLeaf
     *
     * @return the value of base_menu.isLeaf
     * @mbg.generated
     */
    public Boolean getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.isLeaf
     *
     * @param isleaf the value for base_menu.isLeaf
     * @mbg.generated
     */
    public void setIsleaf(Boolean isleaf) {
        this.isleaf = isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_menu.Status
     *
     * @return the value of base_menu.Status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_menu.Status
     *
     * @param status the value for base_menu.Status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}